const navdata = [
	{
		category:"视频",
		websites:[
			{
				name:"腾讯视频",
				url:"https://v.qq.com/"
			},
			{
				name:"爱奇艺",
				url:"https://www.iqiyi.com/"
			},
			{
				name:"优酷视频",
				url:"https://youku.com/"
			},
			{
				name:"芒果TV",
				url:"https://www.mgtv.com/"
			},
			{
				name:"哔哩哔哩",
				url:"https://www.bilibili.com/"
			},
			{
				name:"抖音",
				url:"https://www.douyin.com/"
			},
			{
				name:"CCTV",
				url:"https://tv.cctv.com/"
			},
			{
				name:"厂长资源",
				url:"https://czzy.top/"
			},
			{
				name:"其它1",
				url:"https://www.mjwo.net/"
			},
			{
				name:"其它2",
				url:"https://www.dadaqu.cc/"
			},
			{
				name:"其它3",
				url:"https://fofoys.com/"
			}
			
		]
	},
	{
		category:"音乐",
		websites:[
			{
				name:"网易云音乐",
				url:"https://music.163.com/"
			},
			{
				name:"酷我音乐",
				url:"https://kuwo.cn/"
			},
			{
				name:"QQ音乐",
				url:"https://y.qq.com/"
			},
			{
				name:"九酷",
				url:"https://www.9ku.com/"
			},
			{
				name:"抖音音乐平台",
				url:"https://music.douyin.com/console"
			},
			{
				name:"腾讯启明星",
				url:"https://y.qq.com/venus/#/venus/ai-audio/list"
				
			},
			{
				name:"网易天音",
				url:"https://tianyin.music.163.com/#/"
			}
		]
	},
	{
		category:"程序",
		websites:[
			{
				name:"菜鸟教程",
				url:"https://www.runoob.com/"
			},
			{
				name:"w3school",
				url:"https://www.w3school.com.cn/"
			},
			{
				name:"NWjs",
				url:"https://nwjs.io/"
			},
			{
				name:"HarmonyOS",
				url:"https://developer.huawei.com/consumer/cn/teaching-video/"
			},
			{
				name:"HTML5+",
				url:"https://www.html5plus.org/doc/zh_cn/io.html"
			},
			{
				name:"Puppeteer",
				url:"https://pptr.nodejs.cn/"
			},
			{
				name:"threeJS",
				url:"http://www.webgl3d.cn/pages/aac9ab/"
			},
			{
				name:"Jimp(npm)",
				url:"https://www.npmjs.com/package/jimp"
			},
			{
				name:"仓颉",
				url:"https://cangjie-lang.cn/"
			},
			{
				name:"github",
				url:"github.com"
			}
		]
	},
	{
		category:"工具",
		websites:[
			{
				name:"可画封面制作",
				url:"https://www.canva.cn/"
			},
			{
				name:"sms短信服务",
				url:"https://sms-activate.io/cn"
			},
			{
				name:"百度翻译",
				url:"https://fanyi.baidu.com/mtpe-individual/multimodal#/"
			},
			{
				name:"厂长资源",
				url:"https://www.zhanlian.net/"
			},
			{
				name:"词语查询",
				url:"https://kmcha.com/"
			},
			{
				name:"天地图",
				url:"https://www.tianditu.gov.cn/"
			},
			{
				name:"百度地图",
				url:"https://map.baidu.com/"
			},
			{
				name:"12306",
				url:"https://www.12306.cn/index/"
			},
			{
				name:"携程网",
				url:"https://www.ctrip.com/"
			}
		]
	},
	{
		category:"AI工具",
		websites:[
			{
				name:"deepseek",
				url:"https://chat.deepseek.com/"
			},
			{
				name:"豆包AI",
				url:"https://www.doubao.com/chat/"
			},
			{
				name:"元宝",
				url:"https://yuanbao.tencent.com/chat/naQivTmsDa"
			},
			{
				name:"千问",
				url:"https://www.qianwen.com/"
			},
			{
				name:"kimi",
				url:"https://www.kimi.com/zh/"
			},
			{
				name:"即梦",
				url:"https://jimeng.jianying.com/ai-tool/home"
			},
			{
				name:"通义万相",
				url:"https://tongyi.aliyun.com/wan/"
			},
			{
				name:"混元3D",
				url:"https://3d.hunyuan.tencent.com/"
			},
			{
				name:"sora2国内",
				url:"https://sora2.mineai.app/"
			},
			{
				name:"白日梦",
				url:"https://aibrm.com/"
			},
			{
				name:"豆绘AI",
				url:"https://www.douhuiai.com/"
			},
			{
				name:"hf-mirror模型下载",
				url:"https://hf-mirror.com/"
			},
			{
				name:"魔塔模型下载",
				url:"https://www.modelscope.cn/my/overview"
			},
			{
				name:"bgsubAI抠图",
				url:"https://zh.bgsub.com/webapp/"
			},
			{
				name:"AI图片工具",
				url:"https://photokit.com/?lang=zh"
			},
			{
				name:"vegaAI画图",
				url:"https://vegaai.net/text2Image"
			}
		]
	},
	{
		category:"直播",
		websites:[
			{
				name:"哔哩哔哩",
				url:"https://live.bilibili.com/"
			},
			{
				name:"虎牙直播lol",
				url:"https://www.huya.com/g/lol/"
			},
			{
				name:"斗鱼直播lol",
				url:"https://www.douyu.com/g_LOL"
			}
		]
	},
	{
		category:"游戏",
		websites:[
			{
				name:"碧蓝航线wiki",
				url:"https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5"
			},
			{
				name:"FGOwiki",
				url:"https://m.fgo.wiki/w/%E9%A6%96%E9%A1%B5"
			},
			{
				name:"LOL官网",
				url:"https://lol.qq.com/main.shtml"
			},
			{
				name:"英雄联盟LPL",
				url:"https://lpl.qq.com/"
			},
			{
				name:"云顶资料",
				url:"https://tactics.tools/zh/info/set-12/tables/augments"
			},
			{
				name:"云顶官方",
				url:"https://lol.qq.com/tft/#/index"
			},
			{
				name:"BLHX",
				url:"../blhx/blhx.html"
			}
		]	
	},
	{
		category:"剧本网",
		websites:[
			{
				name:"紫兴剧本网",
				url:"http://zxjuben.com/"
			},
			{
				name:"华语剧本网",
				url:"https://www.juben.pro/"
			},
			{
				name:"剧本网98",
				url:"https://www.juben98.com/"
			},
			{
				name:"版权保护中心",
				url:"https://www.ccopyright.com.cn/"
			},
			{
				name:"抖几句",
				url:"https://www.doujiju.com/"
			},
			{
				name:"腾讯创作平台",
				url:"https://mp.v.qq.com/homepage"
			}
		]
	},
	{
		category:"购物",
		websites:[
			{
				name:"京东",
				url:"https://www.jd.com/"
			},
			{
				name:"淘宝",
				url:"https://www.taobao.com/"
			},
			{
				name:"小米商城",
				url:"https://www.mi.com/"
			},
			{
				name:"华为商城",
				url:"https://www.vmall.com/index.html"
			},
			{
				name:"OPPO",
				url:"https://www.opposhop.cn/"
			},
			{
				name:"VIVO",
				url:"https://shop.vivo.com.cn/"
			},
			{
				name:"ZTE中兴",
				url:"https://www.ztemall.com/"
			},
			{
				name:"荣耀",
				url:"https://www.honor.com/cn/"
			},
			{
				name:"魅族",
				url:"https://www.meizu.com/index.html"
			},
			{
				name:"realme",
				url:"https://www.realme.com/cn/"
			}
		]
	},
	{
		category:"运营商",
		websites:[
			{
				name:"中国移动",
				url:"https://shop.10086.cn/mall_100_100.html"
			},
			{
				name:"中国联通",
				url:"https://www.10010.com/wt_service_web/index.html#/"
			},
			{
				name:"中国电信",
				url:"https://www.189.cn/cq/"
			},
			{
				name:"中国广电",
				url:"https://www.10099.com.cn/index.html"
			}
		]
	},
	{
		category:"云服务",
		websites:[
			{
				name:"华为云",
				url:"https://activity.huaweicloud.com/"
			},
			{
				name:"腾讯云",
				url:"https://cloud.tencent.com/"
			},
			{
				name:"阿里云",
				url:"https://www.aliyun.com/"
			},
			{
				name:"百度云",
				url:"https://cloud.baidu.com/"
			}
		]
	}
]
